language: ruby
rvm:
- 2.0.0
env:
- DB=postgresql
before_script:
- psql -c 'create database jamal_test' -U postgres
script:
- RAILS_ENV=test bundle exec rake --trace db:migrate
- bundle exec rspec spec
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: oBIhRplevd1r/5ySsJaRqUFEZFXwOSV4LrnAI/pqErHbyx/bQguCBA6tY0GJ81Hs/ed7bjFGnXFxfydvMf4DUD1m4fRY16noi7zRHutEn1gfXqFBjHW/Z9jGSTA+II7pF4MPzjIhqeZ+3mOsO1JhZ/dXnUMeqjMUbe4udil6zgY=
  app: jamal-demo
  on:
    repo: guivinicius/jamal
  run:
  - rake db:migrate
